language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build:static
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t afuning/next-web:latest .
  - docker push afuning/next-web:latest